# Generated by Django 2.2 on 2021-05-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20210521_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='users',
        ),
    ]
